window:
  opacity: 0.75
colors:
  # Default colors
  primary:
    background: '0x001520'
    foreground: '0xeeeeee'
  # Normal colors
  normal:
    black:   '0x333333'
    red:     '0xff3c00'
    green:   '0xb1e244'
    yellow:  '0xffc300'
    blue:    '0x5760ff'
    magenta: '0xe600c0'
    cyan:    '0x00ffff'
    white:   '0xeee8d5'

  # Bright colors
  bright:
    black:   '0x888800'
    red:     '0xff0000'
    green:   '0x00ff00'
    yellow:  '0xffff00'
    blue:    '0x0000ff'
    magenta: '0xff00ff'
    cyan:    '0x00ffff'
    white:   '0xffffff'
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    # family: monospace
    family: Menlo

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: monospace
    family: Menlo

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    # family: monospace
    family: Menlo

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Point size
  size: 9.50
  # env
